### ISSUE TITLE
IsCommandTrigger wrong method for getting hidden trigger

### ISSUE THREAD

**Issue by SKProCH** [Lomztein/Advanced-Discord-Commands#1]
I think what here: 
https://github.com/Lomztein/Advanced-Discord-Commands/blob/838f99d8b271ac6fb0e16059269ec7f57e75be0e/Advanced-Discord-Commands/Extensions/CharExtensions.cs#L23-L29
Should be something like that:
```
            if (character == searcher.GetTrigger (owner))
                return true;

            if (character == searcher.GetHiddenTrigger (owner)) {
                isHidden = true;
                return true;
            }
```
At least it would be logical, probably. 

---------------
P.S. Is the project abandoned or are you ready to develop it further?

**Comment by Lomztein** [comment]
Yes, it should be using GetHiddenTrigger instead as you've figured out. Good catch, I'll implement the fix. I believe this might actually be the cause of an issue I've been meaning to look in to.

The project isn't truly abandoned, but I don't have any particular plans for it either. Its primary purpose is to provide a command framework for my own Discord bot. Both projects are currently in late beta for an indeterminate time, as I work on other stuff as well as focus on university.
